import "@cloudbase/framework-plugin-website";
import "@cloudbase/framework-plugin-node";
import "@cloudbase/framework-plugin-nuxt";
import "@cloudbase/framework-plugin-function";
import "@cloudbase/framework-plugin-container";
import "@cloudbase/framework-plugin-dart";
import "@cloudbase/framework-plugin-database";
import "@cloudbase/framework-plugin-deno";
import "@cloudbase/framework-plugin-next";
